name: prettier format check

on:
  push:
    branches: main
  pull_request:
    branches: ['**']

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install dependencies
        working-directory: ./src
        run: npm ci

      - name: run prettier check
        working-directory: ./src
        run: npx prettier . --check
